import { fileURLToPath } from 'node:url'
export const assets = new Map([
  ['/', { file: fileURLToPath(new URL('../../web/index.html', import.meta.url)), type: 'text/html; charset=utf-8' }],
  ['/style.css', { file: fileURLToPath(new URL('../../web/style.css', import.meta.url)), type: 'text/css; charset=utf-8' }],
  ['/client.js', { file: fileURLToPath(new URL('../client/client.js', import.meta.url)), type: 'text/javascript; charset=utf-8' }],
  ['/prompt-client.js', { file: fileURLToPath(new URL('../client/prompt-client.js', import.meta.url)), type: 'text/javascript; charset=utf-8' }],
  ['/models-client.js', { file: fileURLToPath(new URL('../client/models-client.js', import.meta.url)), type: 'text/javascript; charset=utf-8' }],
  ['/models-directory-client.js', { file: fileURLToPath(new URL('../client/models-directory-client.js', import.meta.url)), type: 'text/javascript; charset=utf-8' }],
  ['/archive-client.js', { file: fileURLToPath(new URL('../client/archive-client.js', import.meta.url)), type: 'text/javascript; charset=utf-8' }],
  ['/workspace-client.js', { file: fileURLToPath(new URL('../client/workspace-client.js', import.meta.url)), type: 'text/javascript; charset=utf-8' }],
  ['/workspace-layout.js', { file: fileURLToPath(new URL('../client/workspace-layout.js', import.meta.url)), type: 'text/javascript; charset=utf-8' }],
  ['/protocols/view.js', { file: fileURLToPath(new URL('../client/protocols/view.js', import.meta.url)), type: 'text/javascript; charset=utf-8' }],
  ['/protocols/modules.js', { file: fileURLToPath(new URL('../client/protocols/modules.js', import.meta.url)), type: 'text/javascript; charset=utf-8' }],
  ['/session-client.js', { file: fileURLToPath(new URL('../client/session-client.js', import.meta.url)), type: 'text/javascript; charset=utf-8' }],
  ['/run-change-client.js', { file: fileURLToPath(new URL('../client/run-change-client.js', import.meta.url)), type: 'text/javascript; charset=utf-8' }],
  ['/tool-trace.js', { file: fileURLToPath(new URL('../client/tool-trace.js', import.meta.url)), type: 'text/javascript; charset=utf-8' }],
  ['/session-view.js', { file: fileURLToPath(new URL('../client/session-view.js', import.meta.url)), type: 'text/javascript; charset=utf-8' }],
  ['/draft-client.js', { file: fileURLToPath(new URL('../client/draft-client.js', import.meta.url)), type: 'text/javascript; charset=utf-8' }],
  ['/file-client.js', { file: fileURLToPath(new URL('../client/file-client.js', import.meta.url)), type: 'text/javascript; charset=utf-8' }],
  ['/file-view.js', { file: fileURLToPath(new URL('../client/file-view.js', import.meta.url)), type: 'text/javascript; charset=utf-8' }],
  ['/harness/project-files/domain.js', { file: fileURLToPath(new URL('../harness/project-files/domain.js', import.meta.url)), type: 'text/javascript; charset=utf-8' }],
  ['/image-client.js', { file: fileURLToPath(new URL('../client/image-client.js', import.meta.url)), type: 'text/javascript; charset=utf-8' }],
  ['/harness/image/limits.js', { file: fileURLToPath(new URL('../harness/image/limits.js', import.meta.url)), type: 'text/javascript; charset=utf-8' }],
  ['/harness/image/port.js', { file: fileURLToPath(new URL('../harness/image/port.js', import.meta.url)), type: 'text/javascript; charset=utf-8' }],
  ['/harness/view/decode.js', { file: fileURLToPath(new URL('../harness/view/decode.js', import.meta.url)), type: 'text/javascript; charset=utf-8' }],
  ['/legacy-state.js', { file: fileURLToPath(new URL('../client/legacy-state.js', import.meta.url)), type: 'text/javascript; charset=utf-8' }],
  ['/harness-client.js', { file: fileURLToPath(new URL('../client/harness-client.js', import.meta.url)), type: 'text/javascript; charset=utf-8' }],
  ['/connections-view.js', { file: fileURLToPath(new URL('../client/connections-view.js', import.meta.url)), type: 'text/javascript; charset=utf-8' }],
])

